scrap:
  chrome-driver-path: C:\ocr\chromedriver\chromedriver.exe
  is-hide: false
  save-path:
    excel: C:\ocr\excel\
    image: C:\ocr\image\

spring:
  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
  datasource:
    url: jdbc:mysql://localhost:3306/scraping?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always